table transacoes
	lineageTag: b5efe53a-cc8a-4ecf-ab5d-74cd3df20d1f

	measure 'Valor Total' = SUM(transacoes[Total])
		displayFolder: Medidas
		lineageTag: ad20926d-954d-4a42-b7c1-4b9c26c74afe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cotação corrigida' = ```
			
			
			VAR __DataCtx = MAX(calendario[Data]) 
			
			VAR __UltimaDataComCotacao = 
			    CALCULATE(
			        LASTNONBLANK(calendario[Data], [Cotação do dia]),
			        calendario[Data] <= __DataCtx
			    )
			
			RETURN
			    CALCULATE(
			        [Cotação do dia],
			        calendario[Data] = __UltimaDataComCotacao
			    )
			
			```
		displayFolder: Medidas
		lineageTag: 843baf86-0564-4fee-9bff-e7f23ac82a15

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total R$' = ```
			
			SUMX(
			    moedas,
			    SUMX(
			        calendario,
			        COALESCE([Cotação corrigida], 1) * [Valor Total] 
			    )
			) 
			
			```
		displayFolder: Medidas
		lineageTag: 66eabdbe-a6e0-4798-88ca-4902a84bfa0b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Data
		dataType: dateTime
		formatString: dd/mm/yyyy
		displayFolder: Colunas
		lineageTag: 16b6c2f4-0506-470e-b367-42a524eac4c6
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Total
		dataType: double
		displayFolder: Colunas
		lineageTag: 17e84dbe-51f1-4a32-8ffd-9535b2216863
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: 1e511a0a-e86c-4d2d-b66b-8c091b0c93dd
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	partition transacoes = m
		mode: import
		queryGroup: Facto
		source = ```
				let
				    // Tente abrir a primeira planilha
				    source = Excel.Workbook(File.Contents(base_transacoes), null, true),
				    
				    // Pegue a primeira planilha disponível
				    firstSheet = source{[Item="transacoes",Kind="Sheet"]}[Data],
				    
				    // Ou se não existir com esse nome, pegue a primeira de qualquer jeito
				    fallbackSheet = if firstSheet = null then 
				                       source{0}[Data]
				                    else firstSheet,
				    
				    // Promova a primeira linha como cabeçalho
				    promotedHeaders = Table.PromoteHeaders(fallbackSheet, [PromoteAllScalars=true]),
				    #"Colunas Removidas" = Table.RemoveColumns(promotedHeaders,{"ID"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas",{{"Data", type date}, {"Total", type number}, {"Moeda", type text}})
				in
				    #"Tipo Alterado"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

